title: "The Trade Guys"
email: TradeGuys@csis.org
description: >- # this means to ignore newlines until "baseurl:"
  Trade Guys Scott Miller and Bill Reinsch explain trade, how it affects policy, and how it impacts your day-to-day in ways that everyone can understand. The Trade Guys is hosted by H. Andrew Schwartz and produced by Yumi Araki at the Center for Strategic and International Studies (CSIS), a nonpartisan think tank in Washington, D.C.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tradeguys.csis.org" # the base hostname & protocol for your site, e.g. http://example.com

date_format: '%B %d, %Y'

collections:
  posts:
    title: Trade Explained
    output: true
    permalink: "/trade-explained/:slug/"
  podcast:
    title: Podcast
    output: true
    path: "/podcast/:slug/"
  authors:
    title: Authors
    output: true
    path: "/authors/:slug/"
  series:
    title: Series
    output: true
    path: "/series/:slug/"
  keywords:
    title: Tags
    output: true
    path: "/tags/:slug/"
defaults:
- scope:
    path: ''
  values:
    image: /assets/images/Podcast_TradeGuys_cover-medium.jpg
- scope:
    path: ''
    type: 'posts'
  values:
    layout: post
    permalink: "/trade-explained/:slug/"
    breadcrumbs: true
    breadcrumbs_text: breadcrumbs_all_articles
    sidebar: post-sidebar-post.html
- scope:
    path: ''
    type: 'podcast'
  values:
    layout: post
    permalink: "/podcast/:slug/"
    breadcrumbs: true
    breadcrumbs_text: breadcrumbs_all_podcast
    sidebar: post-sidebar-podcast.html
- scope:
    path: ''
    type: 'authors'
  values:
    layout: archive
    permalink: "/authors/:slug/"
- scope:
    path: ''
    type: 'series'
    permalink: "/series/:slug/"
  values:
    layout: archive
    permalink: "/series/:slug/"
- scope:
    path: ''
    type: 'keywords'
  values:
    layout: archive
    permalink: "/tag/:slug/"

google_analytics: UA-124740679-1
soundcloud_client_id: e1b9039f824fdaf6ec1fc594037c1ac7

twitter:
  card: summary
logo: /assets/images/Podcast_TradeGuys_cover-medium.jpg

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - frasco.config.js
  - FRASCO-DEFAULTS.md
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
  - prettier.config.js
