---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  label: Build Status
  path: NETLIFY.md
  read_only: true
- type: directory
  path: _podcast
  label: Podcast
  create: all
  match: "**/*"
  templates:
  - podcast
- type: jekyll-posts
  label: Trade Explained
  create: all
  templates:
  - trade-explained
  - video
  - external-commentary
- type: directory
  path: _series
  label: Series
  create: all
  match: "**/*"
  templates:
  - series
- type: directory
  path: _keywords
  label: Tags
  create: all
  match: "**/*"
  templates:
  - tag
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: DATA
- type: document
  path: _data/content_types.yaml
  label: Content Types
- type: document
  path: _data/language.yml
  label: Language
- type: document
  path: _data/menus.yml
  label: Menus
- type: document
  path: _data/related_links.yml
  label: Related Links
- type: document
  path: _data/trade_guys.yml
  label: Trade Guys
upload_dir: trade-guys
public_path: https://res.cloudinary.com/csisideaslab/image/upload
front_matter_path: https://res.cloudinary.com/csisideaslab/image/upload
use_front_matter_path: true
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
